- src/App.css
- src/components/map.js
- src/pages/home.tsx
- src/pages/login.js
- src/pages/signup.js
- src/types.ts
- src/util/firebase/chain.ts
- src/util/firebase/firebaseConfig.ts
- src/util/firebase/user.ts
Rendered of chains from db:
Done:
- fetched data from db 
- displayed chains on map 
To do:
> render chains from db

- package.json
- public/locales/en/translation.json
- public/locales/nl/translation.json
- src/components/LanguageSwitcher.tsx
- src/components/Navbar.tsx
- src/i18n.tsx
- src/index.tsx
- src/pages/home.tsx
- src/pages/login.js
- src/pages/signup.js
- yarn.lock
Issue #6 
- Added react-i18next
- Hooked up existing components with react-i18next
- Added sample translations for EN/NL
- Created a dummy language changer component and added it to navbar
> Added internationalization with react-i18next

- public/locales/en/translation.json
- public/locales/nl/translation.json
- src/App.tsx
- src/components/Navbar.tsx
- src/components/map.js
- src/pages/chains/chain.tsx
- src/pages/home.tsx
- src/pages/login.js
- src/pages/signup.js
- src/types.ts
- src/util/firebase/chain.ts
- src/util/firebase/user.ts
First draft of chain details page. Added it under /chains/chainId, which might be useful for admins.
Check it out with for example: http://localhost:3000/chains/4dULvpW6kZO50nvNYOjl
Still to do:
- Authorization
- Sub menu with tab for member list and tab for chain details
- Editing and removing members
- CSV download
> Add chain details page with list of members

- src/App.css
- src/App.tsx
- src/components/Map.js
- src/pages/NewChainLocation.js
- src/util/firebase/chain.ts
- src/util/theme.ts
Implemented map functionality for the new chain flow and displayed chain description to cards - (issues: #4, #35)
The map gets rendered based on the user's browser location (API used: [IPINFO](https://ipinfo.io)). The user can select onClick the location on the map and a pop up displays information on the selected location (used [revered geocoding](https://docs.mapbox.com/api/search/geocoding/) to get locality data).
User can add a description for the new chain and post data (coordinates, description and chain name) to DB.
Done:
To do:
> WIP - new chain map functionality

- src/components/Map.js
- src/pages/NewChainLocation.js
- src/util/api.ts
Implementation of the map, it now renders based on the user location ( #15 )
> rendering map on user location

- package.json
- public/locales/en/translation.json
- public/locales/nl/translation.json
- src/App.css
- src/App.tsx
- src/components/Map.js
- src/components/TextField.tsx
- src/pages/Chain/ChainMemberList.tsx
- src/pages/NewChainSignup.js
- src/pages/Signup.js
- src/pages/UserEdit.js
- src/util/firebase/user.ts
- yarn.lock
Fixes https://github.com/pim0223/clothing-chain-frontend/issues/27
> Edit members

- package.json
- public/index.html
- src/pages/Signup.js
- yarn.lock
Implementation of the sign-up form: new user can introduce an address using the autofill functionality of Mapbox geocoding, which generates a prefilled form with the selected address.
> added geocoding functionality to signup form

- src/App.tsx
- src/components/Navbar.tsx
- src/pages/Signup.js
- src/pages/SignupPage.js
Signup form logic is now a reusable component. Also, introduced a new `SignupPage` which renders the Signup component for the user sign up flow.
> Implemented logic for Signup functionality

- src/App.tsx
- src/pages/ChainEdit.js
- src/pages/ChainMemberList.tsx
- src/pages/UserEdit.js
- src/pages/signup.js~Stashed changes
- src/types.ts
- src/util/firebase/chain.ts
Host can edit their chain's details: address and description (#23) - updates data on Firebase and renders the updated details.
> edit chain's details

- frontend/src/App.css
- frontend/src/App.tsx
- frontend/src/components/FormFields.js
- frontend/src/components/Navbar.tsx
- frontend/src/pages/Map.js
- frontend/src/pages/NewChainLocation.js
- frontend/src/pages/NewChainSignup.js
- frontend/src/pages/Signup.js
Fixed bug on `Signup` form for the phone number input.
Made some changes on the UI: 
- `About` is the new home
- `Map` has a separate page 
- Reviewed the styling for the map pop-ups 
- Introduced filter functionality for categories and search bar 
- Updated the 'create new chain' flow (TO REVIEW)
> UI changes

- frontend/src/App.css
- frontend/src/pages/ChainEdit.js
- frontend/src/pages/ChainMemberList.tsx
- frontend/src/pages/ChainsList.js
- frontend/src/pages/FindChain.tsx
- frontend/src/util/firebase/chain.ts
- frontend/src/util/firebase/user.ts
- implemented publish chain functionality and update db (to view: /chains/members/chainId)
- replaced useForm with Formik when editing a chain and update db (to view: chains/edit/chainId)
TO DO: 
- update list of chains with relevant information
- add chainAdmin information on single chain page
> Admin pages: publish and edit chains

- firebase/functions/.eslintrc.js
- frontend/src/App.tsx
- frontend/src/pages/NewChainSignup.tsx
- frontend/src/pages/PrivacyPolicy.tsx
- frontend/src/pages/Signup.tsx
Update to add a privacy statement to the signup pages and link to a new page to later be filled with a privacy statement
> Privacy statement

- frontend/src/App.css
- frontend/src/App.tsx
- frontend/src/components/Navbar.tsx
- frontend/src/pages/ChainEdit.js
- frontend/src/pages/ChainMemberList.tsx
- frontend/src/pages/ChainsList.js
- frontend/src/pages/FindChain.tsx
- frontend/src/pages/NewChainSignup.tsx
- frontend/src/pages/UserEdit.js
Routing naming update: replaced 'chains' with 'loops' across all URLs
> updated routing naming to loops

- frontend/src/pages/FindChain.tsx
New feature: No matches found message added.
Bugfix: setSearchTerm() at line 147 was causing problems. Instead, now it finds matches and triggers re-render when it is done.
Bugfix: When the user clears the input, it was still showing the last result. Now it clears the result as well.
> loop search optimization (#91)

- .github/workflows/deploy-firebase-acc.yml
- .github/workflows/deploy-firebase-prod.yml
- firebase/functions/src/index.ts
- frontend/src/pages/Contacts.js
- frontend/src/util/firebase/mail.ts
- New firebase function was added to receive contact form data and send emails.
- mail.ts file created for email related firebase functions
- contacts page edited
- workflow configuration files edited
> Contact mail

- frontend/package.json
- frontend/public/locales/en/translation.json
- frontend/public/locales/nl/translation.json
- frontend/src/App.css
- frontend/src/App.tsx
- frontend/src/components/GeocoderSelector.js
- frontend/src/components/Layouts.tsx
- frontend/src/components/formActions.tsx
- frontend/src/pages/ChainMemberList.tsx
- frontend/src/pages/ChainsList.js
- frontend/src/pages/FindChain.tsx
- frontend/src/pages/Geocoding.tsx
- frontend/src/pages/Login.tsx
- frontend/src/pages/LoginEmailFinished.tsx
- frontend/src/pages/NewChainSignup.tsx
- frontend/src/pages/Signup.tsx
- frontend/src/pages/Thankyou.tsx
- frontend/src/util/theme.ts
- frontend/yarn.lock
Fixed few styling bugs on `FindChain`component and on some MUI library components.
Signup forms redesign: 
- styled the`Signup` component
- styled the`NewChainSignup` component
- styled `Login` component
- implemented internationalization across relevant pages
> Signup styling and minor fixes

- frontend/netlify.toml
Added Google Fonts to Netlify headers
> added google fonts to netlify headers

- frontend/public/locales/en/translation.json
- frontend/public/locales/nl/translation.json
- frontend/src/App.css
- frontend/src/components/CategoriesDropdown.tsx
- frontend/src/components/GeocoderSelector.js
- frontend/src/components/Layouts.tsx
- frontend/src/components/SearchBar.tsx
- frontend/src/components/SizesDropdown.tsx
- frontend/src/images/right-arrow-white.svg
- frontend/src/pages/ChainEdit.js
- frontend/src/pages/ChainMemberList.tsx
- frontend/src/pages/ChainsList.js
- frontend/src/pages/NewChainSignup.tsx
- frontend/src/pages/Signup.tsx
- frontend/src/pages/UserEdit.js
- frontend/src/util/theme.ts
Redesigned the following pages:
- ChainEdit.js
- UserEdit.js
- ChainsList.js
In ChainsList.js - I removed the 'Active Users' field from the table view as it was slowing down page load. 
Thought about a new approach to further implement that feature on issue #140
> Admin actions pages redesign

- frontend/src/pages/FindChain.tsx
- frontend/yarn.lock
#133
- Converted from programmatically mapping chains to `<Marker>` to declaratively displaying it with `<Source>` and `<Layer>`
- Used GeoJSON
- So far styling (radius, color, etc.) is hardcoded and just make do
> Clustering (#133)

- frontend/src/App.tsx
- frontend/src/components/ChainsProvider.tsx
- frontend/src/components/Counters/Counters.tsx
- frontend/src/pages/ChainsList.js
- frontend/src/pages/FindChain.tsx
- frontend/src/pages/Home.tsx
- frontend/src/util/firebase/chain.ts
#136
- Refactor all `getChains()` call to be called only once in `ChainsProvider` context
- Remove `getChainsLength()` and replace it with calling `.length` on `chains` from `ChainsProvider`
> Use React Context for chains #136

- frontend/src/pages/ChainEdit.js
- frontend/src/pages/Contacts.js
- frontend/src/pages/NewChainLocation.tsx
- frontend/src/pages/NewChainSignup.tsx
- frontend/src/pages/Signup.tsx
- frontend/src/pages/UserEdit.js
Fixes a few issues to do with forms:
* Slow responsiveness of text inputs (#147) mitigated by running form validation logic only on input blur, rather than on every change
* Fixes confusion between fields in contact form that was resulting in name being sent in place of the message. Also cleaning up code to use Formik props for form values.
* Fixes a few inconsistencies in validation requirements
> Form fixes

- frontend/netlify.toml
- frontend/src/pages/About.tsx
- frontend/src/pages/PrivacyPolicy.tsx
- frontend/src/pages/TermsOfUse.tsx
Updated copy for Privacy Policy and Terms of Use statements.
> Legal copy update

- frontend/src/components/Newsletter/Newsletter.tsx
Addresses issue #173 
Added confirmation message when signing up to the newsletter
> added confirmation message

- firebase/firestore.rules
Issue #183 
Firebase rules update: allowing chainAdmin to publish its own loop
> updated Firebase rule for chainAdmin

- firebase/functions/.eslintrc.js
- firebase/functions/src/index.ts
- firebase/functions/src/payments.ts
> Edit .eslintrc.json and reformat files

- frontend/src/App.css
- frontend/src/pages/About.tsx
- frontend/src/pages/Home.tsx
> fixed iframe styling

- .github/workflows/deploy-firebase-acc.yml
- .github/workflows/deploy-firebase-prod.yml
- firebase/functions/package-lock.json
- firebase/functions/package.json
- firebase/functions/src/index.ts
- frontend/src/components/Newsletter/Newsletter.tsx
Fix #184 but add user to mailing list upon sign up instead of upon the scenarios listed in the issue.
Also storing subscription status/data to Mailchimp instead of Firestore
> Mailchimp integration

- frontend/src/pages/About.tsx
- frontend/src/pages/Home.tsx
Updated Vimeo iframe controls visibility
> vimeo url update

- frontend/.gitignore
- frontend/src/App.tsx
- frontend/src/components/Donation/Donation.module.css
- frontend/src/components/Donation/Donation.module.scss
- frontend/src/components/Donation/DonationCompleted.tsx
- frontend/src/components/Donation/DonationForm.tsx
- frontend/src/pages/Donations/Donate.tsx
For this feature, I've also:
- updated Firebase functions configs with live keys (kept test keys for acc env)
- updated Github relevant secrets 
- added a thank-you message if payment is successful
> Donations update

- .github/workflows/deploy-firebase-acc.yml
- .github/workflows/deploy-firebase-prod.yml
Added public Stripe key to GitHub environment configs for deployment
> updated .yml files

- frontend/src/App.tsx
- frontend/src/components/FindChain/ChainNotFound.tsx
- frontend/src/components/Footer.tsx
- frontend/src/components/Navbar.tsx
- frontend/src/pages/ChainMemberList.tsx
- frontend/src/pages/FindChain.tsx
- frontend/src/pages/NewChainLocation.tsx
- frontend/src/pages/NewChainSignup.tsx
> Rest ful api

- frontend/public/locales/en/translation.json
- frontend/public/locales/nl/translation.json
- frontend/src/App.css
- frontend/src/components/CategoriesDropdown.tsx
- frontend/src/components/ChainDetailsForm.tsx
- frontend/src/components/FormFields.js
- frontend/src/components/formActions.tsx
- frontend/src/pages/NewChainLocation.tsx
- frontend/src/pages/NewChainSignup.tsx
- frontend/src/util/theme.ts
- removed interested sizes field from `NewChainSignup`
- added popovers with explanatory text to `NewChainLocation` form
- updated the layout of `NewChainLocation` form
- copy update
> New loop location form update

- frontend/public/locales/en/translation.json
- frontend/public/locales/nl/translation.json
- frontend/src/pages/NewChainSignup.tsx
- frontend/src/pages/Signup.tsx
- frontend/src/util/theme.ts
- updated error msg on signup forms
- added helper link on signup forms
- updated login error msg
> Error messages

- frontend/src/components/Layouts.tsx
- frontend/src/pages/Donations/DonationCompleted.tsx
- frontend/src/pages/Home.tsx
- frontend/src/pages/Login.tsx
- frontend/src/pages/Signup.tsx
- frontend/src/pages/Thankyou.tsx
- Add MEAX logo
- Add image credit for Anke Teunissen
> Add credit to more photos #358

- frontend/src/components/DataExport.tsx
- Removes the unfinished newsletter value for the csv export
- Change sizes values to; baby, 1_to_4, 5_to_12, women_s, women_m, women_l, women_plus, men_s, men_m, men_l, men_plus
> Remove newsletter from csv and improve sizes #399

- frontend/public/locales/en/translation.json
- frontend/src/pages/FindChain.tsx
This just needs the "AreYouSureJoinLoop" translation key added to the other languages
> When loggedin join 2 step q #396

- frontend/src/components/Counters/Counters.tsx
- frontend/src/components/FindChain/SearchBar.tsx
- frontend/src/components/Navbar.tsx
- frontend/src/components/Newsletter.tsx
- frontend/src/components/Testimonials.tsx
- frontend/src/pages/Home.tsx
accessibility improvements tested on an Ipad successfully.
> accessibility improvements

- frontend/src/components/Footer.tsx
> refract: footer copyright

- app/src/pages/HelpList.tsx
- frontend/src/components/Footer.tsx
Hi There, 
I'm interested in helping out on the project and seen that issue #496 ( [Change LinkedIn link ](https://github.com/the-clothing-loop/website/issues/496)) needed fixed urgently. Seemed like a simple fix so I went ahead and made the change, works correctly in the dev enviroment :)
I also noticed that the old link is being used in this file:
`app/src/pages/HelpList.tsx`
I can also make the change for that if you like, should it be a separate issue/ pull request?
Thanks!
Martin
> Change LinkedIn link

- server/sql/Finding all hosts:
- server/sql/find-all-hosts.sql
SELECT u.email, uc.is_chain_admin 
FROM users AS u
JOIN user_chains AS uc ON uc.user_id = u.id 
GROUP BY u.id 
HAVING uc.is_chain_admin = TRUE AND u.email is not NULL
> Create Finding all hosts

- frontend/src/components/Footer.tsx
**Description:**
Added the Play Store and the App Store icon to the footer section. Along with that, added functionality to detect the Mobile OS and show the respective logo hiding the other one.
Related to Issue #538 
Files Modified: `frontend/src/components/Footer.tsx`
**Screenshot:**
> Modify: Add Play Store and App Store icon to footer

- frontend/public/locales/en/translation.json
- frontend/src/api/route.ts
- frontend/src/api/types.ts
- frontend/src/pages/ChainMemberList.tsx
- server/internal/controllers/route.go
- server/internal/server.go
- server/pkg/tsp/mst.go
- server/pkg/tsp/tsp.go
Adding route optimization for a loop on the Members List page
Related issue #343 
https://github.com/the-clothing-loop/website/assets/29601619/bc91379f-3ea6-4e16-9e2f-4e1dd2a530fc
> Optimize route order

- server/internal/app/database.go
- server/internal/app/mail.go
- server/internal/controllers/chain.go
- server/internal/controllers/contact.go
- server/internal/controllers/cron.go
- server/internal/controllers/login.go
- server/internal/controllers/poke.go
- server/internal/models/mail_retry.go
- server/internal/models/mail_retry_e2e_test.go
- server/internal/models/testmain_test.go
- server/internal/server.go
- server/internal/tests/integration_tests/mail_e2e_test.go
- server/internal/tests/mocks/mock-tables.go
- server/internal/views/email.go
- server/internal/views/email_test.go
Fixes #578 
To test this;
1. login to a normal user
2. Switch off mailpit in docker desktop 
3. Join a loop from the website 
4. Switch on mailpit in docker
5. Wait a day or change the created_at value in the database 
6. Restart the server
7. Mailpit should show the mail and the record in the db should be gone
> Mail retry

- server/internal/controllers/bag.go
- server/internal/views/notifications.go
> add notification if someone else sets you to a bag

- bruno/login/begin login & register chain.bru
- bruno/login/begin login.bru
- bruno/login/logout.bru
- bruno/login/register basic user.bru
- bruno/login/register chain admin.bru
- bruno/login/validate login & register chain.bru
- bruno/login/validate login.bru
- frontend/public/locales/en/translation.json
- frontend/src/App.tsx
- frontend/src/api/login.ts
- frontend/src/api/user.ts
- frontend/src/components/AddressForm.tsx
- frontend/src/pages/AdminDashboard.tsx
- frontend/src/pages/Login.tsx
- frontend/src/pages/LoginEmailFinished.tsx
- frontend/src/pages/Signup.tsx
- frontend/src/pages/Thankyou.tsx
- frontend/src/providers/AuthProvider.tsx
- server/internal/controllers/login.go
- server/internal/controllers/users.go
- server/internal/models/chain.go
- server/internal/models/user.go
- server/internal/models/user_chain.go
- server/internal/server.go
- server/internal/services/email.go
- server/internal/tests/integration_tests/mail_e2e_test.go
- server/internal/tests/integration_tests/modals_chain_e2e_test.go
- server/internal/tests/integration_tests/modals_chain_user_e2e_test.go
- server/internal/tests/integration_tests/modals_user_e2e_test.go
- server/internal/views/email.go
This PR allows the user to log in when joining a Loop.
Related PR: https://github.com/the-clothing-loop/website/pull/605 Because there were some differences between the master branch and the previous branch, it was better for me to create a new branch rather than try to fix the merging issues
Related issue: https://github.com/the-clothing-loop/website/issues/431
Preview
https://github.com/the-clothing-loop/website/assets/29601619/bfd2455d-1db1-4824-825f-54d2af8a37a6
https://github.com/the-clothing-loop/website/assets/29601619/850d6dfd-e210-4d77-87a1-e76ca43a8ac2
https://github.com/the-clothing-loop/website/assets/29601619/8ac0fc02-4bdb-43c1-808a-3859a0c24ccb
https://github.com/the-clothing-loop/website/assets/29601619/3a30c7fc-21fb-426b-a92f-d134943d54b3
> allow users to login when join a lopp

- app/src/pages/Settings.tsx
https://github.com/the-clothing-loop/website/issues/676
> Hide description element when loop description is empty

- app/public/locales/en/translation.json
- app/src/components/Chat/ChatWindow.tsx
- app/src/pages/Chat.tsx
Adds a modal for renaming or deleting a channel
> Modal for rename and delete channel options

- frontend/src/components/react/components/ChainDetailsForm.tsx
Only requires sizes for clothing categories when creating a loop
> Ignore interested sizes books toys #750

- frontend/src/components/react/pages/ChainMemberList.tsx
https://github.com/the-clothing-loop/website/issues/860
> Delay route number update on mobile (on input blur and Enter key press)
